### ISSUE TITLE
Dark Mode UI - Can't read text

### ISSUE THREAD

**Issue by lexvoid** [lexDAO/Kali#127]
The current dark mode version of the UI leaves text in the "Dashboard", "Proposals" and "New Proposal" page to be quite unreadable in the body and in the buttons. 

![KaliDAO - Google Chrome 12_27_2021 7_19_11 PM (2)](https://user-images.githubusercontent.com/32367643/147477968-56825349-0d24-4df9-b0d9-7656f50c4b2a.png)

**Comment by nerderlyne** [comment]
improved readability!
