### ISSUE TITLE
Open links in new tab 

### ISSUE THREAD

**Issue by lexvoid** [lexDAO/Kali#128]
Please add functionality to open all embedded links in a new tab for ease of reference and interfacing.

**Comment by nerderlyne** [comment]
which links do you mean?

**Comment by lexvoid** [comment]
I think the link to the DAO documentation? Operating agreement, UNA, code of conduct etc.

**Comment by nerderlyne** [comment]
cool will have them open in a new tab when we add those links

**Comment by lexvoid** [comment]
Awesome, thank you! :)
