### ISSUE TITLE
Feature: DAO data double-check

### ISSUE THREAD

**Issue by lexvoid** [lexDAO/Kali#145]
Is it feasible to add a page for previewing the finalized DAO data-points prior to deployment so the end-user is able to review the structure and confirms before paying for the deploy txn.

**Comment by nerderlyne** [comment]
![Screenshot from 2022-01-03 10-52-00](https://user-images.githubusercontent.com/13903299/147901550-0606e3b6-12ea-4c0d-a161-66c42e507580.png)
There's a preview now. Do you mean something else?

**Comment by lexvoid** [comment]
perfecto! tyyy
