### ISSUE TITLE
Ragequit Option

### ISSUE THREAD

**Issue by Karotoka** [lexDAO/Kali#149]
At founding on new UX, I was told that I could customize certain specs. However, a possibility to turn off ragequit never seemed to appear.

I actually have a usecase that will require a DAO that has no rage quit.

Thoughts?

**Comment by z0r0z** [comment]
Hey @Karotoka Unlike Moloch, we separate ragequit out into a `redemption` extension. So, users can deploy a DAO and not have immediate economic redemption rights. I think we're good here :~)
