### ISSUE TITLE
Attack Vector: Arbitrary Call proposal

### ISSUE THREAD

**Issue by nerderlyne** [lexDAO/Kali#23]
require supermajority AND a time period > 1 hour to pass

**Comment by z0r0z** [comment]
coming back to this, I am thinking this attack feels perhaps not worth hardcoding safeguards past the UI. For example, if a DAO is deployed with a voting period less than 1 hour.... this will likely be a mistake and the users would not put assets into DAO. If they did it on purpose, they are likely pros that will watch proposals closely. lmk what you think

**Comment by z0r0z** [comment]
le resolved
