### ISSUE TITLE
Allow Spaces Between Deployer Address/Shares

### ISSUE THREAD

**Issue by z0r0z** [lexDAO/Kali#27]
currently the deployer UI requires elements to be packed together, like so 
![image](https://user-images.githubusercontent.com/92001561/143736047-de784b71-6586-4501-adf0-7cb9b62e66e1.png)

for many users, it will likely be more intuitive for them to use spaces, so if we can support both, that seems useful.

otherwise, is there a different format for deploying multiple founders?

**Comment by z0r0z** [comment]
in terms of other approaches here is how daohaus handles inputs 
![image](https://user-images.githubusercontent.com/92001561/143783666-4d69d42c-6eca-47c9-977b-04a8920b15cd.png)

**Comment by z0r0z** [comment]
aragon allows rows to be created with separation of inputs 
![image](https://user-images.githubusercontent.com/92001561/143783720-a6c582c7-6935-40b1-b94c-0f0f6514a1dd.png)

**Comment by nerderlyne** [comment]
liking the Aragon design. we should go with that!

**Comment by z0r0z** [comment]
agreed, I think rows are most intuitive

**Comment by nerderlyne** [comment]
implemented aragon design! it do look ugly rn tho
