### ISSUE TITLE
Gasless "Join DAO" proposal 

### ISSUE THREAD

**Issue by nerderlyne** [lexDAO/Kali#32]
Add gasless proposal to join the DAO so non-members can join

**Comment by z0r0z** [comment]
cool stuff. So imagine this will be storing the details of a `MINT` membership proposal in Kali db, and then simulating Moloch-style "sponsorship" where an existing member essentially makes a `MINT` proposal with these details.

**Comment by nerderlyne** [comment]
as discussed we should shaft this for now because it might invite spammers

"sponsorship" happening at the social layer(discord, twitter) seems better
