### ISSUE TITLE
Support Arrays in Proposals

### ISSUE THREAD

**Issue by z0r0z** [lexDAO/Kali#41]
KaliDAO proposals allow for multiple actions to be batched together.

For example, someone can make a proposal to mint shares to multiple accounts. 

To expose this functionality, we should likely add the ability to add `+` rows for `accounts`, which automatically creates a row for `amounts`, and similar.

**Comment by jordanteague** [comment]
started doing this - currently supported on Send Shares proposal type.  will add for Burn Shares and Send Token - possibly Extensions, as well?
