### ISSUE TITLE
Externally transferred shares not reflected

### ISSUE THREAD

**Issue by trtius** [lexDAO/Kali#56]
Transferring tokens outside of kali app appears to have no effect on membership or voting shares.
I sent some TERT to another address, and still was able to vote with 100% of shares. Other address is not a member and is unable to vote.

**Comment by jordanteague** [comment]
@trtius were you able to vote using the wallet where you transferred the shares? or with the old wallet no longer holding the shares?

**Comment by jordanteague** [comment]
I wonder if share transfer was paused, and they never left your wallet?
