### ISSUE TITLE
select menus do not get covered up by loading screen

### ISSUE THREAD

**Issue by jordanteague** [lexDAO/Kali#65]
this may be because they've been given a bg color - perhaps we should remove?

**Comment by nerderlyne** [comment]
On removing bg 
some way to do both? 
![Screenshot from 2021-12-07 03-55-27](https://user-images.githubusercontent.com/13903299/144932844-fbc505d4-b338-4c16-8608-3dce39c68146.png)

**Comment by jordanteague** [comment]
will close this issue for now since we're going to be doing a design refactor, and may move away from a full screen loader - will reopen if still applicable after redesign
